[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
  Referrer-Policy = "no-referrer-when-downgrade"
  X-XSS-Protection = "1; mode=block"
  Permissions-Policy = "geolocation=(), microphone=(), camera=()"
  Cross-Origin-Embedder-Policy = "require-corp"